#!python
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from functools import reduce

class Fib():
	def __init__(self, max):
		self.a = None
		self.b = 1
		self.max = max

	def __iter__(self):
		return self

	def __next__(self):
		if self.a is None:
			self.a = self.b
			self.b = 1
			return 1
		r = self.a + self.b
		if r > self.max:
			raise StopIteration
		self.a = self.b
		self.b = r
		return r


print(reduce(lambda x, y: x+y, filter(lambda i: i%2==0,Fib(4000000))))